### ISSUE TITLE
ImportError: No module named 'OverrideAudit.lib'

### ISSUE THREAD

**Issue by FichteFoll** [OdatNurd/OverrideAudit#27]
### Summary

Fails to load; lots of greyed-out menu items in the context menu due to commands not being available.

```
reloading plugin OverrideAudit.override_audit
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/home/fichte/.config/sublime-text-3/Installed Packages/OverrideAudit.sublime-package/override_audit.py", line 24, in <module>
ImportError: No module named 'OverrideAudit.lib'
```

### How to Reproduce

1. Start ST

### Environment

- Sublime Text build: 3156
- OverrideAudit version: v1.1.1
- Operating System: Arch Linux
- Case Sensitive Filesystem: Yes

**Comment by OdatNurd** [comment]
I can't replicate this on a fresh install of that build; was this something that was working previously and then stopped working? Is there perhaps a partially unpacked version as well?

The version of the code in the `master` branch has gone through a Big Scary Refactor :tm: that changes the layout of some of the code, although the `lib` folder is still untouched. 

As such even if you had an unpacked version I would expect that although things might go pear shaped, it wouldn't be here. However the way the modules are loaded was slightly changed between the two, which might be getting in the way.

**Comment by FichteFoll** [comment]
Doesn't seem like I can reproduce anymore. I just noticed this on two individual  but consecutive startups, but am not seeing it with 3157 anymore. The update could or could not have an influence here.

Closing until I find a repro.
