### ISSUE TITLE
[BUG] Unable to open diff for package with a `*` in its name

### ISSUE THREAD

**Issue by FichteFoll** [OdatNurd/OverrideAudit#29]
### Summary

Unable to open diff for package with a `*` in its name.

### How to Reproduce

From the override overview, which looks as follows:

```
WARNING: Showing only expired overrides!
WARNING: Non-expired overrides may exist!

Report Generated: 2019-02-20 13:31:49

[ IU] Swift for F*ing Sublime
  `- [X] Swift.sublime-syntax
```

When I right-click on `Swift.sublime-syntax` and request a diff for the file, the exception below occurs.

### Actual Behaviour

```
Traceback (most recent call last):
  File "/home/fichte/.config/sublime-text-3/Installed Packages/OverrideAudit.sublime-package/lib/threads.py", line 96, in <lambda>
  File "/home/fichte/.config/sublime-text-3/Installed Packages/OverrideAudit.sublime-package/override_audit.py", line 1371, in <lambda>
  File "/home/fichte/.config/sublime-text-3/Installed Packages/OverrideAudit.sublime-package/override_audit.py", line 1381, in _pkg_loaded
  File "/home/fichte/.config/sublime-text-3/Installed Packages/OverrideAudit.sublime-package/lib/packages.py", line 715, in __getitem__
KeyError: 'ing Sublime'
```

### Environment

- Sublime Text build: 3190
- OverrideAudit version: v1.2.1
- Operating System: Arch Linux
- Case Sensitive Filesystem: Yes

**Comment by OdatNurd** [comment]
This issue revolves around the syntax definitions in OverrideAudit explicitly excluding characters that are not valid in file names on Windows as listed in the [PackageControl Naming Guidelines](https://packagecontrol.io/docs/submitting_a_package#Step_2) under the assumption that packages won't be named that. 

Triggering commands from reports relies on the syntax definition to provide the information on the package and override name to work with. The diff will open without incident if you manually open the file and trigger the command from there, for example.

In this case, that package works on Linux and MacOS, but Package Control can't install it on Windows because it uses the package name as the file name and the python runtime rejects it (see below).

Since the package works on the other systems, I would say that it's something that should be fixed here; if not by allowing those characters in package (and resource) names then at least by rejecting the entire package name as invalid instead of picking up partway through as it does currently.

I assume it's not common but also not unheard of for packages with these characters to be added to the default channel. As one of the PC team members, do you think it's worth raising an issue on their tracker to perhaps exclude this package from being installed on Windows since it won't work there?

```
ignored packages updated to: ["GitGutter", "Swift for F*ing Sublime", "TypeScript", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Exception in thread Thread-27:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "D:\Program Files\Sublime Text 3\Data\Installed Packages\Package Control.sublime-package\package_control/package_installer.py", line 202, in run
    self.result = self.manager.install_package(self.package)
  File "D:\Program Files\Sublime Text 3\Data\Installed Packages\Package Control.sublime-package\package_control/package_manager.py", line 1127, in install_package
    with open_compat(tmp_package_path, "wb") as package_file:
  File "D:\Program Files\Sublime Text 3\Data\Installed Packages\Package Control.sublime-package\package_control/open_compat.py", line 22, in open_compat
    return open(path, mode, encoding=encoding, errors=errors)
OSError: [Errno 22] Invalid argument: 'c:\\users\\micro\\appdata\\local\\temp\\tmp8m_g1r\\Swift for F*ing Sublime.sublime-package'

ignored packages updated to: ["GitGutter", "TypeScript", "Vintage"]
```

**Comment by OdatNurd** [comment]
Based on the knowledge that packages added to the official channel repository are vetted to ensure that their names don't include invalid characters and that the package above is coming from a channel file that wasn't subjected to that vetting (and that the author is [renaming the package](https://github.com/colinta/Swift-for-f-ing-sublime/issues/20), for now I'm going to close this as it seems like the official intention should be that such packages shouldn't be allowed.
